// Manual relatório = relatório not generated by the PNAE app (`link_pdf IS NULL` + indicador 4550);
// the atendimento row is identical to app-created ones, and the relatório is stored as two pictures:
// `relatorio` is the signed printed relatório, `foto` is proof of visit.
export type AtendimentoComRelatorioManualQueryDTO = {
  pageSize?: number;
  cursor?: string;
  id_usuario?: string;
  id_reg_empresa?: string | null;
};

export type ProdutorResumoDTO = {
  nm_pessoa: string | null;
  nr_cpf_cnpj: string | null;
  dap: string | null;
  caf: string | null;
};

export type PropriedadeResumoDTO = {
  nome_propriedade: string;
  geo_ponto_texto: string | null;
};

export type AtendimentoClienteResumoDTO = {
  produtor: ProdutorResumoDTO;
  propriedade: PropriedadeResumoDTO | null;
};

export type AtendimentoUsuarioResumoDTO = {
  id_usuario: string;
  nome_usuario: string | null;
  id_und_empresa: string | null;
};

// One Demeter `at_arquivo` projected for the list. `idArquivo` is a BigInt serialized to string by
// the gateway scalar; `tipoArquivo` is the raw stored MIME (frontend derives actions from it);
// `nomeArquivo` is an app-generated presentation name, never Demeter's `nome_arquivo`.
export type ArquivoRelatorioManualResumoDTO = {
  idArquivo: string;
  tipoArquivo: string;
  nomeArquivo: string;
};

export type AtendimentoComRelatorioManualItemDTO = {
  id_at_atendimento: string;
  data_inicio_atendimento: string;
  data_fim_atendimento: string | null;
  data_validacao: string | null;
  data_atualizacao: string;
  data_criacao: string;
  data_sei: string | null;
  data_see: string | null;
  sn_pendencia: number | null;
  sn_validado: number | null;
  dt_update_record: string | null;
  id_at_anterior: string | null;
  id_und_empresa: string;
  ativo: boolean;
  clientes: AtendimentoClienteResumoDTO[];
  usuarios: AtendimentoUsuarioResumoDTO[];
  arquivos: ArquivoRelatorioManualResumoDTO[];
};

export type AtendimentoComRelatorioManualPageGqlDTO = {
  items: AtendimentoComRelatorioManualItemDTO[];
  pageSize: number;
  nextCursor: string | null;
  hasMore: boolean;
};

export type AtendimentoComRelatorioManualDTO = Omit<
  AtendimentoComRelatorioManualItemDTO,
  'clientes' | 'usuarios'
> & {
  produtor: ProdutorResumoDTO | null;
  propriedade: PropriedadeResumoDTO | null;
  usuario: AtendimentoUsuarioResumoDTO | null;
  nomeMunicipio: string | null;
  id_reg_empresa: string | null;
  nomeRegional: string | null;
};

export type AtendimentoComRelatorioManualPageDTO = {
  items: AtendimentoComRelatorioManualDTO[];
  pageSize: number;
  nextCursor: string | null;
  hasMore: boolean;
};
