services:
  pnae_backend_dev:
    image: pnae_backend_dev
    container_name: pnae_backend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - development.env
    command: "npm run start:dev"
    volumes:
      - ./:/home/node/app
      - /home/pnae/pnae_app/data_dev:/home/node/data_dev
      - /home/pnae/pnae_app/logs/dev:/home/node/logs
      - /home/pnae/pnae_app/zipFiles/dev:/home/node/zipFiles
    deploy:
       replicas: 1
       resources:
        limits:
          cpus: '3'
          memory: 4096M
    restart: always
    networks:
      - pnae_dev

networks:
  pnae_dev:
    external: true
