services:
  pnae_backend_dev:
    container_name: pnae_backend_dev
    image: pnae_backend_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - development.env
    environment:
      - NODE_ENV=development
    entrypoint: "dockerize -wait tcp://postgres_pnae_dev:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "npm run start:dev"
    # ports:
    #   - '3001:3000'
    depends_on:
      - postgres_pnae_dev
    volumes:
      - ./:/home/node/app
      - ${HOST_FOLDER}/data_dev:${FILES_FOLDER}
      - ../logs/dev:/${LOGS_FOLDER}
    networks:
      - pnae_dev_default

  postgres_pnae_dev:
    container_name: postgres_pnae_dev
    image: postgres:16
    env_file:
      - development.env
    ports:
      - '5433:5432'
    volumes:
      - ${DB_FOLDER}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - pnae_dev_default

volumes:
  pg_data:
    external: true
networks:
  pnae_dev_default:
    external: true
