services:
  pnae_backend_hmg:
    image: pnae_backend_hmg
    build:
      context: .
      dockerfile: ./Dockerfile.hmg
    env_file:
      - homolog.env
    entrypoint: "dockerize -wait tcp://postgres_pnae_hmg:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "npm run start:dev"
    volumes:
      - ./:/home/node/app
      - /home/pnae/pnae_app/data_hmg:/home/node/data_hmg
      - /home/pnae/pnae_app/logs/hmg:/home/node/logs
      - /home/pnae/pnae_app/zipFiles/hmg:/home/node/zipFiles
    networks:
      - pnae_hmg_default
    depends_on:
      - postgres_pnae_hmg

  postgres_pnae_hmg:
    container_name: postgres_pnae_hmg
    image: postgres:16
    ports:
      - '5434:5432'
    env_file:
      - homolog.env
    volumes:
      - postgres_data_hmg:/var/lib/postgresql/data
    restart: always
    networks:
      - pnae_hmg_default
  # prisma-migrate:
  #   image: pnae_backend_hmg
  #   container_name: prisma_migrate
  #   command: npx prisma db push
  #   env_file:
  #     - homolog.env
  #   working_dir: /home/node/app/prisma
  #   depends_on:
  #     - postgres_pnae_hmg
  #   networks:
  #     - pnae_hmg_default

volumes:
  postgres_data_hmg:


networks:
  pnae_hmg_default:
    external: true
