version: '3.9'
services:
  pnae_backend_prod:
    container_name: pnae_backend_prod
    image: pnae_backend_prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
    ports:
      - "3200:3200"
    entrypoint: "dockerize -wait tcp://postgres_pnae_prod:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "npm run start:prod"

    volumes:
      - ${HOST_FOLDER}/data:${FILES_FOLDER}
    networks:
      - pnae_prod_default
    depends_on:
      - postgres_pnae_prod

  postgres_pnae_prod:
    container_name: postgres_pnae_prod
    image: postgres:16
    ports:
      - '5434:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file:
      - production.env
    networks:
      - pnae_prod_default
  # prisma-migrate:
  #   image: pnae_backend_prod
  #   container_name: prisma_migrate
  #   command: npx prisma db push
  #   env_file:
  #     - production.env
  #   depends_on:
  #     - postgres_pnae_prod
  #   networks:
  #     - pnae_prod_default

volumes:
  postgres_data_prod:


networks:
  pnae_prod_default:
    external: true
