services:
  pnae_backend_hmg:
    image: pnae_backend_hmg
    container_name: pnae_backend_hmg
    build:
      context: .
      dockerfile: ./Dockerfile.hmg
    env_file:
      - homolog.env
    command: "npm run start:prod"
    init: true
    volumes:
      - /home/pnae/pnae_app/data_dev:/home/node/data_dev
      - /home/pnae/pnae_app/logs/hmg:/home/node/logs
      - /home/pnae/pnae_app/zipFiles/hmg:/home/node/zipFiles
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '3'
          memory: 4096M
    restart: always
    networks:
      - pnae_hmg_default

networks:
  pnae_hmg_default:
    external: true
