version: '3.9'
services:
  pnae_backend_hmg:
    container_name: pnae_backend_hmg
    image: pnae_backend_hmg
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
    ports:
      - "3100:3100"
    entrypoint: "dockerize -wait tcp://postgres_pnae_hmg:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "npm run start:prod"
    volumes:
      - ${HOST_FOLDER}/data_hmg:${FILES_FOLDER}
    networks:
      - pnae_hmg_default
    depends_on:
      - postgres_pnae_hmg

  postgres_pnae_hmg:
    container_name: postgres_pnae_hmg
    image: postgres:16
    ports:
      - '5434:5432'
    volumes:
      - postgres_data_hmg:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - pnae_hmg_default
  # prisma-migrate:
  #   image: pnae_backend_hmg
  #   container_name: prisma_migrate
  #   command: npx prisma db push
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres_pnae_hmg
  #   networks:
  #     - pnae_hmg_default

volumes:
  postgres_data_hmg:


networks:
  pnae_hmg_default:
    external: true
