FROM node:lts-slim

RUN apt-get update -y && \
    apt-get install -y procps openssl && \
    rm -rf /var/lib/apt/lists/*

COPY ./lib/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb /home/node/app/lib/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb
RUN apt-get update && \
    apt-get install -y /home/node/app/lib/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb && \
    rm -rf /var/lib/apt/lists/* /home/node/app/lib/wkhtmltox_0.12.6.1-3.bookworm_amd64.deb

RUN usermod -u 1001 node && \
    groupmod -g 1001 node && \
    chown -R node:node /home/node/app && \
    mkdir -p /home/node/logs && chown -R node:node /home/node/logs

WORKDIR /home/node/app
USER node
