version: '3.9'
services:
  pnae_backend_prod:
    image: pnae_backend_prod
    build:
      context: .
      dockerfile: ./Dockerfile.prod
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    env_file:
      - production.env
    entrypoint: "dockerize -wait tcp://postgres_pnae_prod:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "npm run start:prod"
    volumes:
      - /home/pnae/pnae_app/data:/home/node/data
      - /home/pnae/pnae_app/logs/prod:/home/node/logs
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
    restart: always
    networks:
      - pnae_prod_default
    depends_on:
      - postgres_pnae_prod

  postgres_pnae_prod:
    container_name: postgres_pnae_prod
    image: postgres:16
    ports:
      - '5435:5432'
    env_file:
      - production.env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: always
    networks:
      - pnae_prod_default
  # prisma-migrate:
  #   image: pnae_backend_prod
  #   container_name: prisma_migrate
  #   command: npx prisma db push
  #   env_file:
  #     - production.env
  #   depends_on:
  #     - postgres_pnae_prod
  #   networks:
  #     - pnae_prod_default

volumes:
  postgres_data_prod:


networks:
  pnae_prod_default:
    external: true
