version: '3.9'
services:
  pnae_backend_hmg:
    image: pnae_backend_hmg
    build:
      context: .
      dockerfile: ./Dockerfile.hmg
      args:
        - HOST_UID=${HOST_UID}
        - HOST_GID=${HOST_GID}
    env_file:
      - homolog.env
    # ports:
    #   - "3100:3100"
    entrypoint: "dockerize -wait tcp://postgres_pnae_hmg:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "npm run start:prod"
    volumes:
      - /home/pnae/pnae_app/data_hmg:/home/node/data_hmg
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    restart: "on-failure"
    networks:
      - pnae_hmg_default
    depends_on:
      - postgres_pnae_hmg

  postgres_pnae_hmg:
    container_name: postgres_pnae_hmg
    image: postgres:16
    ports:
      - '5434:5432'
    env_file:
      - homolog.env
    volumes:
      - postgres_data_hmg:/var/lib/postgresql/data
    networks:
      - pnae_hmg_default
  # prisma-migrate:
  #   image: pnae_backend_hmg
  #   container_name: prisma_migrate
  #   command: npx prisma db push
  #   env_file:
  #     - homolog.env
  #   depends_on:
  #     - postgres_pnae_hmg
  #   networks:
  #     - pnae_hmg_default

volumes:
  postgres_data_hmg:


networks:
  pnae_hmg_default:
    external: true
