name: pnae_infra

services:
  postgres_pnae_hmg:
    container_name: postgres_pnae_hmg
    image: postgres:16
    ports:
      - '5434:5432'
    env_file:
      - homolog.env
    volumes:
      - postgres_data_hmg:/var/lib/postgresql/data
    restart: always
    networks:
      - pnae_hmg_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis_hmg:
    image: redis:alpine
    container_name: redis_hmg
    ports:
      - "6379:6379"
    networks:
      - pnae_hmg_default
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_hmg:
    external: true
    name: backend_postgres_data_hmg

networks:
  pnae_hmg_default:
    external: true
