export const formattedValues = [
  ['ENTRADA', 'Entrada'],
  ['SAIDA', 'Saída'],
  ['BAIXO', 'Baixo'],
  ['ALTO', 'Alto'],
  ['MODERADO', 'Moderado'],
  ['ATIVIDADE_PRIMARIA', 'Atividade Primária'],
  ['ATIVIDADE_SECUNDARIA', 'Atividade Secundária'],
  ['AMBAS', 'Ambas'],
  ['NAO_POSSUI', 'Não possui'],
  ['NAO_SE_APLICA', 'Não se aplica'],
  ['ASSOCIACAO', 'Associação'],
  ['OUTROS', 'Outros'],
  ['PF', 'Pessoa Física'],
  ['PJ', 'Pessoa Jurídica'],
  ['COLETIVA', 'Coletiva'],
  ['FAMILIAR', 'Familiar'],
  ['CERTIDAO_USO_INSIGNIFICANTE', 'Certidão de Uso Insignificante'],
  ['CERTIDAO_DISPENSA_LICENCIAMENTO', 'Certidão de Dispensa de Licenciamento'],
  ['VIGILANCIA_SANITARIA', 'Vigilância Sanitária'],
  [true, 'Sim'],
  [false, 'Não'],
];
