export const formattedValues = [
  ['ENTRADA', 'Entrada'],
  ['SAIDA', 'Saída'],
  ['BAIXO', 'Baixo'],
  ['ALTO', 'Alto'],
  ['MODERADO', 'Moderado'],
  ['MODERADO', 'MÉDIO'],
  ['ATIVIDADE_PRIMARIA', 'Atividade Primária'],
  ['ATIVIDADE_PRIMARIA', 'Atividade Primária (Produtos in natura)'],
  ['ATIVIDADE_SECUNDARIA', 'Atividade Secundária'],
  ['ATIVIDADE_SECUNDARIA', 'Atividade Secundária (Agroindústria)'],
  ['AMBAS', 'Ambas'],
  ['NAO_POSSUI', 'Não possui'],
  ['NAO_SE_APLICA', 'Não se aplica'],
  ['ASSOCIACAO', 'Associação'],
  ['COOPERATIVA', 'Cooperativa'],
  ['OUTROS', 'Outros'],
  ['OUTRAS', 'Outras'],
  ['PF', 'Pessoa Física'],
  ['PJ', 'Pessoa Jurídica'],
  ['COLETIVA', 'Coletiva'],
  ['FAMILIAR', 'Familiar'],
  ['CERTIDAO_USO_INSIGNIFICANTE', 'Certidão de uso insignificante'],
  ['OUTORGA', 'Outorga'],
  ['CERTIDAO_DISPENSA_LICENCIAMENTO', 'Certidão de dispensa de licenciamento'],
  ['LICENCA_AMBIENTAL', 'Licença ambiental'],
  ['VIGILANCIA_SANITARIA', 'Vigilância Sanitária'],
  ['IMA', 'IMA (Instituto Mineiro de Agropecuária)'],
  ['MAPA', 'MAPA (Ministério da Agricultura, Pecuária e Abastecimento)'],
  ['SIM', 'SIM (Serviço de Inspeção Municipal - Consórcio)'],

  [true, 'Sim'],
  [false, 'Não'],
];
